
spring:
  application:
    name: tank-server
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8082

map:
  path: src/main/resources/maps

